### ISSUE TITLE
Allow running "dotnet-setversion" at the solution level

### ISSUE THREAD

**Issue by pms1969** [TAGC/dotnet-setversion#1]
Added the xml snippet to all my csproj files, and get the error message:
` No executable found matching command "dotnet-setversion"`

I've obviously got something wrong..  Any ideas?

This is VS2017 15.3 preview2 and DotNetCore 2.0 preview 2 csprojs

**Comment by pms1969** [comment]
ah-ha.  doesn't work at the solution level....  but seems to be working at a project level.  How do I do this at a solution level?

**Comment by pms1969** [comment]
And additionally, if i run this in the microsoft/dotnet:2.0-sdk docker image, I get the following error:
```
root@79f59544b01b:~/app/implementation/Configuration# dotnet setversion 0.0.1
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.
root@79f59544b01b:~/app/implementation/Configuration#
```

**Comment by TAGC** [comment]
The dotnet:2.0-sdk thing is a separate issue (can be reposted as a new issue). For the solution level thing, I'm not sure it's possible to create solution-level CLI tools (what I've inferred from reading [this](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility)).

I just include the tool in each project within a solution. At the solution level I have a bash script that `cd`'s into each project directory and invokes the CLI command:

```bash
for d in src/* test/*
do
    cd $d
    dotnet setversion $1
    cd ../..
done
```

This assumes you want each project in a solution to have identical versions.

**Comment by pms1969** [comment]
Pretty much what I did.  Thanks.  I'll post the dotnet:2.0-sdk issue separately for you.

This is sooooo handy, that you might want to thing about contributing it back to the cli tool main branch, then it would be solution level.

**Comment by TAGC** [comment]
Since .NET Core transitioned back to *.csproj format, it's allowed doing things like `$ dotnet build /property:"Version=1.2.3"`, and this works at a solution level. My tool works a little differently, and doing it the "official" way caused issues for me when I tried it out, but my guess is the in-built way would work okay for most people.

Unless it turns out otherwise, I don't think there's a major need to integrate this tool into the official .NET Core CLI repo.
