### ISSUE TITLE
CI build hangs indefinitely

### ISSUE THREAD

**Issue by TAGC** [TAGC/dotnet-setversion#11]
All Appveyor builds have recently started hanging indefinitely when executing this line:

```
cd src/dotnet-setversion; dotnet setversion $env:VERSION; dotnet pack -c Release -o release/; cd ../..
```

Specifically, `dotnet setversion $env:VERSION` seems to be the issue. The build logs display "Setting version: x.x.x.x" as expected, but the build never progresses beyond this point.

RDP'ing into the build server while a build is running shows this happens with both PowerShell and Command Prompt. Trying to execute `dotnet setversion 1.2.3-4` in one console and displaying the contents of `dotnet-setversion.csproj` in another shows that the version field is getting updated as expected, but that the file also gets prepended with `<?xml version="1.0" encoding="utf-8"?>` (which does not happen when executing the same command locally).

![](https://user-images.githubusercontent.com/1588951/44218052-c8ad2680-a170-11e8-86df-c0c3e94c5abc.png)

**Comment by TAGC** [comment]
As an experiment, I reset `develop` to the last commit that resulted in a successful build (from 5 months back) and force-pushed it.

The [build running now](https://ci.appveyor.com/project/TAGC/dotnet-setversion/build/1.0.19) is hanging despite it handling the exact same commit as the [successful build from 5 months back](https://ci.appveyor.com/project/TAGC/dotnet-setversion/build/1.0.10). This proves that the issue is related to some configuration change on the AppVeyor build servers themselves.

**Comment by OwenMcDonnell** [comment]
Apologies, somehow this issue slipped through the cracks. We're looking into it now and will update you as soon as we can.

**Comment by TAGC** [comment]
@OwenMcDonnell Thanks again. For the record this issue was caused by not specifying a lower-bound on dotnet-setversion's dependency on itself. Doing so allows the builds to run successfully again.

**Comment by TAGC** [comment]
Adding invalid to exclude from changelog
