### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by hampton1122** [TAGC/dotnet-setversion#15]
I am getting the following error:

No executable found matching command "dotnet-setversion"

in my csproj I have:

<ItemGroup>
    <DotNetCliToolReference Include="dotnet-setversion" Version="*"/>
  </ItemGroup>

Any Ideas? I am building in the microsoft/dotnet:2.0.0-sdk image

**Comment by TAGC** [comment]
Version 2.0.0 onwards is installed as a global tool, so the executable is just `setversion` now. [See this part of the README](https://github.com/TAGC/dotnet-setversion#migrating-from-1-to-2).

**Comment by TAGC** [comment]
I'm going to assume this is resolved.
