### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by kavitachana** [TAGC/dotnet-setversion#17]
I just upgraded to .Net Core 3.1 and noticed that the setversion tool no longer works.  After installing, the tool is looking for version 2.1.0 of the Microsoft.NETCore.App framework, but .NET Care 3.1 uses Microsoft.NETCore.App 3.1.1.  Will a release for 3.1 be available in the near future?  Thanks!

![image](https://user-images.githubusercontent.com/20517960/75674530-3e91b980-5c53-11ea-8c24-023c7ee8a5da.png)

**Comment by TAGC** [comment]
No worries. Can you try installing [version 2.2.0-beta0001](https://www.nuget.org/packages/dotnet-setversion/2.2.0-beta0001) of dotnet-setversion and seeing if that works?

**Comment by kavitachana** [comment]
That worked!  Thanks :)
