### ISSUE TITLE
trim trailing newline

### ISSUE THREAD

**Issue by jorisdebock** [TAGC/dotnet-setversion#19]
version read from file should be trimmed, due the possible trailing newline character.

e.g.
```
"0.0.28\n"
```

this will result in the new line character to be in the csproj file

https://github.com/TAGC/dotnet-setversion/blob/c98adf43eca6aad0a7c703eee55ea3fd9577777d/src/dotnet-setversion/Program.cs#L123

**Comment by TAGC** [comment]
Sure I'll get that resolved.

**Comment by TAGC** [comment]
Can you try pulling version `2.2.1-alpha0003` and see if that fixes the issue you're having?
