### ISSUE TITLE
Working with older project formats

### ISSUE THREAD

**Issue by Fungusware** [TAGC/dotnet-setversion#24]
I wonder, does this tool work with the older .NET Framework project files? I seem to be getting errors when using older csproj and vbproj files.

**Comment by TAGC** [comment]
Hi Fungus.

By design this project is only designed to work with the newer csproj files used in .NET Core / .NET 5+ projects. Maybe this will help? https://stackoverflow.com/questions/8446693/specify-assembly-version-number-as-a-command-line-argument-in-msbuild

**Comment by Fungusware** [comment]
I migrated everyhing over to the SDK format. Thanks for the response though!
