### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by melsawy93** [TAGC/dotnet-setversion#25]
Hi, I just discovered this, is this still working? I am trying to run this and getting this:

C:\Users\moustafa.el-sawy\OneDrive\Plugins\Combinito\Combinito>setversion 1.1.1 Combinito.csproj
Unhandled exception. System.InvalidOperationException: This operation would create an incorrectly structured document.
   at System.Xml.Linq.XDocument.ValidateDocument(XNode previous, XmlNodeType allowBefore, XmlNodeType allowAfter)
   at System.Xml.Linq.XDocument.ValidateNode(XNode node, XNode previous)
   at System.Xml.Linq.XContainer.AddNodeSkipNotify(XNode n)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.Add(Object content)
   at dotnet_setversion.Extensions.GetOrCreateElement(XContainer container, String name) in C:\projects\dotnet-setversion\src\dotnet-setversion\Program.cs:line 187
   at dotnet_setversion.Program.SetVersion(String version, String csprojFile) in C:\projects\dotnet-setversion\src\dotnet-setversion\Program.cs:line 150
   at dotnet_setversion.Program.Run(String version, String csprojFile) in C:\projects\dotnet-setversion\src\dotnet-setversion\Program.cs:line 58
   at dotnet_setversion.Program.Run(Options options) in C:\projects\dotnet-setversion\src\dotnet-setversion\Program.cs:line 32
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at dotnet_setversion.Program.Main(String[] args) in C:\projects\dotnet-setversion\src\dotnet-setversion\Program.cs:line 18

**Comment by TAGC** [comment]
Hey, is it okay to post the contents of your csproj file?

**Comment by melsawy93** [comment]
Yes sure. 

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{4F6D9F29-E2B9-4299-9F90-2C930FDBA2A3}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Combinito</RootNamespace>
    <AssemblyName>Combinito</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CSiAPIv1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8a93c9e72eabf762, processorArchitecture=MSIL">
      <HintPath>packages\CSIAPIv1-All.1.25.0\lib\net\CSiAPIv1.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xaml.Behaviors, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\Microsoft.Xaml.Behaviors.Wpf.1.1.39\lib\net45\Microsoft.Xaml.Behaviors.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>packages\Newtonsoft.Json.13.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="Prism, Version=8.1.97.5141, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59, processorArchitecture=MSIL">
      <HintPath>packages\Prism.Core.8.1.97\lib\net47\Prism.dll</HintPath>
    </Reference>
    <Reference Include="Prism.Unity.Wpf, Version=8.1.97.5141, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59, processorArchitecture=MSIL">
      <HintPath>packages\Prism.Unity.8.1.97\lib\net47\Prism.Unity.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Prism.Wpf, Version=8.1.97.5141, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59, processorArchitecture=MSIL">
      <HintPath>packages\Prism.Wpf.8.1.97\lib\net47\Prism.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Data.WPF, Version=20.1460.0.59, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89, processorArchitecture=MSIL">
      <HintPath>packages\Syncfusion.Data.WPF.20.1.0.59\lib\net46\Syncfusion.Data.WPF.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing, Version=20.1460.0.59, Culture=neutral, PublicKeyToken=632609b4d040f6b4, processorArchitecture=MSIL">
      <HintPath>packages\Syncfusion.Licensing.20.1.0.59\lib\net46\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfGrid.WPF, Version=20.1460.0.59, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89, processorArchitecture=MSIL">
      <HintPath>packages\Syncfusion.SfGrid.WPF.20.1.0.59\lib\net46\Syncfusion.SfGrid.WPF.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.WPF, Version=20.1460.0.59, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89, processorArchitecture=MSIL">
      <HintPath>packages\Syncfusion.Shared.WPF.20.1.0.59\lib\net46\Syncfusion.Shared.WPF.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Threading.Tasks.Extensions.4.5.2\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="Unity.Abstractions, Version=5.11.7.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0, processorArchitecture=MSIL">
      <HintPath>packages\Unity.Abstractions.5.11.7\lib\net47\Unity.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Container, Version=5.11.11.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0, processorArchitecture=MSIL">
      <HintPath>packages\Unity.Container.5.11.11\lib\net47\Unity.Container.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase" />
    <Reference Include="WindowsFormsIntegration" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Bootstrapper.cs" />
    <Compile Include="cPlugin.cs" />
    <Compile Include="Models\LComboChange.cs" />
    <Compile Include="Models\SettingsConfig.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="ViewModels\EndSummaryVM.cs" />
    <Compile Include="ViewModels\MainWindowVM.cs" />
    <Compile Include="ViewModels\SettingsWindowVM.cs" />
    <Compile Include="Views\EndSummary.xaml.cs">
      <DependentUpon>EndSummary.xaml</DependentUpon>
    </Compile>
    <Compile Include="Views\MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="Views\SettingsWindow.xaml.cs">
      <DependentUpon>SettingsWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Combination.png" />
    <Resource Include="Resources\Envelope.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Combinito.Business\Combinito.Business.csproj">
      <Project>{F4D59EF1-2724-48D6-B076-04D8B9A5C01B}</Project>
      <Name>Combinito.Business</Name>
    </ProjectReference>
    <ProjectReference Include="..\Combinito.Core\Combinito.Core.csproj">
      <Project>{28902f05-e1c0-4ef1-8d4a-80b9db70e141}</Project>
      <Name>Combinito.Core</Name>
    </ProjectReference>
    <ProjectReference Include="..\Combinito.Services.Interfaces\Combinito.Services.Interfaces.csproj">
      <Project>{E60F69D6-D12E-48F7-A481-675AFEFBA179}</Project>
      <Name>Combinito.Services.Interfaces</Name>
    </ProjectReference>
    <ProjectReference Include="..\Combinito.Services\Combinito.Services.csproj">
      <Project>{cf0f5d5d-a95a-4d60-aa3c-16ccf599553d}</Project>
      <Name>Combinito.Services</Name>
    </ProjectReference>
    <ProjectReference Include="..\Modules\Combinito.Modules.LCombGenerator\Combinito.Modules.LCombGenerator.csproj">
      <Project>{B96561CB-2BFF-4DDB-A3AF-335FB9112F5D}</Project>
      <Name>Combinito.Modules.LCombGenerator</Name>
    </ProjectReference>
    <ProjectReference Include="..\Modules\Combinito.Modules.LCombImporter\Combinito.Modules.LCombImporter.csproj">
      <Project>{4D838356-5AB5-4748-B267-F062CBA3F8D6}</Project>
      <Name>Combinito.Modules.LCombImporter</Name>
    </ProjectReference>
    <ProjectReference Include="..\Modules\Combinito.Modules.LCombModifier\Combinito.Modules.LCombModifier.csproj">
      <Project>{CA7B02AC-E590-4C66-A81F-6BCDF6E64B6E}</Project>
      <Name>Combinito.Modules.LCombModifier</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Page Include="Views\EndSummary.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Views\MainWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Views\SettingsWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\CombinitoLogoShort.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Load.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>`

**Comment by melsawy93** [comment]
Can it be due to my project being a .NET Framework not a .NET Core project?

**Comment by TAGC** [comment]
> Can it be due to my project being a .NET Framework not a .NET Core project?

I'm afraid so yeah, this tool is meant for .NET Core/.NET 5+, it doesn't support .NET Framework.
