### ISSUE TITLE
Support for .NET 7.0

### ISSUE THREAD

**Issue by StephanCasper** [TAGC/dotnet-setversion#26]
Implement support for .NET 7.0 so that this tool can be used in CI build environments that use this framework.

**Comment by TAGC** [comment]
Thanks for raising this. It might take some time to get it released because I'm having issues with AppVeyor.

**Comment by TAGC** [comment]
I've published v2.6.0 of this tool with support for .NET 7. Let me know if you have any issues with it.

**Comment by StephanCasper** [comment]
Works fine, thanks a lot.
