### ISSUE TITLE
Doesn't work for dotnetcore 2.0

### ISSUE THREAD

**Issue by pms1969** [TAGC/dotnet-setversion#3]
If i run this in the microsoft/dotnet:2.0-sdk docker image, I get the following error:
```
root@79f59544b01b:~/app/implementation/Configuration# dotnet setversion 0.0.1
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.
root@79f59544b01b:~/app/implementation/Configuration#
```

Building it and targeting netcore2.0 app and packaging it and using that version works, so it's just a matter of targeting both, or possibly even copying the files into a netcore2.0 target platform in the nuget.

**Comment by TAGC** [comment]
I've reproduced this issue in a Docker container based on `microsoft/dotnet:2.0-sdk`. I've also published a pre-release version that appears to resolve this issue.

Can you reference the pre-release package using `<DotNetCliToolReference Include="dotnet-setversion" Version="1.0.1-bugfix-3-0001" />` in your project and confirm the fix? If it works, I'll publish it as a stable release (v1.0.1).

**Comment by pms1969** [comment]
sorry, haven't forgotten you.  been stuck with a production problem for the last few days.  still ongoing.  I'll confirm as soon as I can.

**Comment by pms1969** [comment]
confirmed.  sorry for the delay.

**Comment by TAGC** [comment]
Cool, I'll publish the next release imminently.
