### ISSUE TITLE
Drop support for .NET Core 2.1, .NET Core 3.1, and .NET 5 

### ISSUE THREAD

**Issue by TAGC** [TAGC/dotnet-setversion#30]
Remove support for .NET Core 2.1, .NET Core 3.1, and .NET 5. These versions of .NET Core / .NET are no longer supported and contain vulnerabilities.

This is raised off of the discussion in #28.

**Comment by paulirwin** [comment]
@TAGC I've submitted a PR #31 that drops this support in case you want to merge that before .NET 8. Otherwise, I'd be happy to update this PR after .NET 8 support is merged and you can just leave it open. No preference on order from my end.
