### ISSUE TITLE
TeamCity integration?

### ISSUE THREAD

**Issue by tofutim** [TAGC/dotnet-setversion#7]
I use TeamCity. I wonder if there is a way to use this without changing any of the csproj files.

**Comment by TAGC** [comment]
If I implement #5 then I guess it should be possible to just copy/install dotnet-setversion over as a binary onto the CI machine during builds and run `dotnet-setversion <path-to-csproj> <version-string>`.

Any reason you don't want to just change the csproj files to add it as a per-project dependency?

**Comment by tofutim** [comment]
Just lazy. Lol. Thanks.

**Comment by TAGC** [comment]
Going to close this for housekeeping. Let me know if you want it re-opened.
