### ISSUE TITLE
Does not handle multiple <PropertyGroup> tags

### ISSUE THREAD

**Issue by mmedic** [TAGC/dotnet-setversion#8]
If csproj file has multiple `<PropertyGroup>` tags and any of them but first have the `<Version>` tag, the tool will not detect it and instead will create a new `<Version>` tag inside of the first `<PropertyGroup>` tag even though a subsequent `<PropertyGroup>` tag already has a `<Version>` tag set. For example:

```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>
<PropertyGroup>
    <Version>123</Version>
</PropertyGroup>
```
In above example, the tool will create a new `<Version>` tag inside of the first `<PropertyGroup>` tag instead of updating the `<Version>` tag inside of the second `<PropertyGroup>` tag.

**Comment by TAGC** [comment]
Thanks for pointing this out. I think I've fixed this and I'll release an update shortly.
